site_name: dev-environment
theme:
  name: material
nav:
  - 이론: 0-os.md
  - setup: 1-setup.md
  - keyboard: 2-keyboard.md
  - code: 3-code.md
docs_dir: docs          #기본값은 docs. 따로 문서 폴더 안만들거기에 루트로.
site_dir: site          #기본값은 site. 따라서 안써도 되지만 그냥 명시
markdown_extensions:
  - toc
  - codehilite